# GitHub Repository Settings Configuration
# This file configures repository settings to minimize conflicts and improve development workflow

repository:
  # Repository description
  description: "Atlas - Enterprise Supply Chain Transparency Platform with AI-powered risk assessment and global compliance monitoring"

  # Repository topics/tags
  topics: "supply-chain, transparency, ai, enterprise, compliance, esg, human-rights, modern-slavery"

  # Repository settings
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main

  # Merge settings to reduce conflicts
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

  # Auto-merge settings
  allow_auto_merge: true

  # Security settings
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews
      required_status_checks:
        strict: true
        contexts:
          - "build"
          - "test"
          - "typecheck"

      # Pull request settings
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: ["atlas-core-team"]

      # Conflict resolution settings
      enforce_admins: false
      allow_force_pushes: false
      allow_deletions: false

      # Auto-merge when checks pass
      required_linear_history: false
      restrictions:
        users: []
        teams: ["atlas-core-team"]

  - name: development
    protection:
      required_status_checks:
        strict: false
        contexts:
          - "build"
          - "typecheck"

      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false

      enforce_admins: false
      allow_force_pushes: true
      allow_deletions: false

# Teams configuration
teams:
  - name: atlas-core-team
    description: "Core development team for Atlas platform"
    privacy: closed
    members:
      - maintainers

  - name: atlas-contributors
    description: "External contributors and community members"
    privacy: closed
    permission: triage

# Labels for issue and PR management
labels:
  # Priority labels
  - name: "priority: critical"
    color: "d73a4a"
    description: "Critical issues that need immediate attention"

  - name: "priority: high"
    color: "fb8500"
    description: "High priority issues"

  - name: "priority: medium"
    color: "ffb700"
    description: "Medium priority issues"

  - name: "priority: low"
    color: "8ac926"
    description: "Low priority issues"

  # Type labels
  - name: "type: bug"
    color: "d73a4a"
    description: "Something isn't working"

  - name: "type: feature"
    color: "0075ca"
    description: "New feature or request"

  - name: "type: enhancement"
    color: "a2eeef"
    description: "Enhancement to existing feature"

  - name: "type: documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"

  - name: "type: refactor"
    color: "fbca04"
    description: "Code refactoring"

  # Component labels
  - name: "component: frontend"
    color: "1d76db"
    description: "Frontend React components and UI"

  - name: "component: backend"
    color: "0e8a16"
    description: "Backend services and APIs"

  - name: "component: database"
    color: "5319e7"
    description: "Database related changes"

  - name: "component: infrastructure"
    color: "fbca04"
    description: "Infrastructure and deployment"

  # Conflict resolution labels
  - name: "status: merge-conflict"
    color: "d73a4a"
    description: "Pull request has merge conflicts"

  - name: "status: needs-rebase"
    color: "fb8500"
    description: "Branch needs to be rebased"

  - name: "status: ready-for-review"
    color: "0e8a16"
    description: "Ready for code review"

  - name: "status: work-in-progress"
    color: "fbca04"
    description: "Work in progress"

  # Auto-merge labels
  - name: "auto-merge"
    color: "0e8a16"
    description: "Automatically merge when checks pass"

  - name: "no-auto-merge"
    color: "d73a4a"
    description: "Do not auto-merge this PR"

# Milestones
milestones:
  - title: "v1.0.0 - Production Release"
    description: "First production release of Atlas platform"
    state: open

  - title: "v1.1.0 - Enterprise Features"
    description: "Enhanced enterprise features and capabilities"
    state: open

  - title: "v1.2.0 - AI & Analytics"
    description: "Advanced AI features and analytics dashboard"
    state: open

# Collaborators and permissions
collaborators:
  # Example collaborators - adjust as needed
  - username: atlas-admin
    permission: admin

  - username: atlas-developer
    permission: maintain

  - username: atlas-contributor
    permission: write

# Repository environments
environments:
  - name: production
    protection_rules:
      - type: required_reviewers
        reviewers:
          - atlas-core-team
      - type: wait_timer
        wait_timer: 5
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false

  - name: staging
    protection_rules:
      - type: required_reviewers
        reviewers:
          - atlas-core-team
    deployment_branch_policy:
      protected_branches: false
      custom_branch_policies: true
      custom_branches:
        - development
        - staging/*

  - name: development
    protection_rules: []
    deployment_branch_policy:
      protected_branches: false
      custom_branch_policies: true
      custom_branches:
        - development
        - feature/*
        - bugfix/*

# Auto-delete head branches
delete_branch_on_merge: true

# Security and analysis
security_and_analysis:
  advanced_security:
    status: enabled
  secret_scanning:
    status: enabled
  secret_scanning_push_protection:
    status: enabled
  dependency_graph:
    status: enabled
  vulnerability_alerts:
    status: enabled

# Pages configuration
pages:
  source:
    branch: gh-pages
    path: /
  build_type: workflow

# Discussions
discussions:
  enabled: true
  categories:
    - name: "General"
      emoji: "💬"
      description: "General discussions about Atlas platform"

    - name: "Ideas"
      emoji: "💡"
      description: "Ideas for new features and improvements"

    - name: "Q&A"
      emoji: "❓"
      description: "Questions and answers about using Atlas"

    - name: "Show and Tell"
      emoji: "🎉"
      description: "Show off your Atlas implementations"
